version: '3.9'
services:
  postgres:
    image: postgres:latest
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      PGDATA: /data/postgres
    restart: unless-stopped
    hostname: postgres
    healthcheck:
      test: exit 0

volumes:
  postgres: